//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EngineeringMath.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibraryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EngineeringMath.Resources.LibraryResources", typeof(LibraryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        public static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imp.
        /// </summary>
        public static string ImperialAbbrev {
            get {
                return ResourceManager.GetString("ImperialAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial.
        /// </summary>
        public static string ImperialFullName {
            get {
                return ResourceManager.GetString("ImperialFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        public static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometers.
        /// </summary>
        public static string Kilometers {
            get {
                return ResourceManager.GetString("Kilometers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Meters {
            get {
                return ResourceManager.GetString("Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string MetricAbbrev {
            get {
                return ResourceManager.GetString("MetricAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric.
        /// </summary>
        public static string MetricFullName {
            get {
                return ResourceManager.GetString("MetricFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Miles {
            get {
                return ResourceManager.GetString("Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeters.
        /// </summary>
        public static string Millimeters {
            get {
                return ResourceManager.GetString("Millimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI.
        /// </summary>
        public static string SIAbbrev {
            get {
                return ResourceManager.GetString("SIAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International System of Units.
        /// </summary>
        public static string SIFullName {
            get {
                return ResourceManager.GetString("SIFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USCS.
        /// </summary>
        public static string USCSAbbrev {
            get {
                return ResourceManager.GetString("USCSAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States Customary Units.
        /// </summary>
        public static string USCSFullName {
            get {
                return ResourceManager.GetString("USCSFullName", resourceCulture);
            }
        }
    }
}
